// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElCheckbox: typeof import('element-plus/es/el-checkbox')['default']
    ElDatePicker: typeof import('element-plus/es/el-date-picker')['default']
    ElDivider: typeof import('element-plus/es/el-divider')['default']
    ElDrawer: typeof import('element-plus/es/el-drawer')['default']
    ElDropdown: typeof import('element-plus/es/el-dropdown')['default']
    ElDropdownItem: typeof import('element-plus/es/el-dropdown-item')['default']
    ElDropdownMenu: typeof import('element-plus/es/el-dropdown-menu')['default']
    ElEmpty: typeof import('element-plus/es/el-empty')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElTag: typeof import('element-plus/es/el-tag')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    TodoDetail: typeof import('./src/components/TodoDetail.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}

export { }
